name: Task
description: Implementation task for pen2pdf
title: ""
labels: []
body:
  - type: textarea
    id: description
    attributes:
      label: Description
      description: What needs to be implemented
    validations:
      required: true
  - type: textarea
    id: acceptance-criteria
    attributes:
      label: Acceptance Criteria
      description: Conditions that must be met to consider this done
      value: |
        - [ ]
    validations:
      required: true
  - type: textarea
    id: technical-notes
    attributes:
      label: Technical Notes
      description: Architecture decisions, dependencies, or constraints
    validations:
      required: false
